name: "Codex task"
description: "Шаблон задачи для Codex: кратко, по делу, с тест-планом"
title: "Codex: <module> — <short topic> — <YYYY-MM-DD>"
labels: ["codex", "tech-debt"]
assignees: []
body:
  - type: textarea
    id: summary
    attributes:
      label: SUMMARY (ru)
      description: 2–5 предложений о сути изменений/рисков
      placeholder: "Краткое описание…"
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: ISSUES & TASKS (ru)
      description: Чёткий чеклист задач
      value: |
        - [ ] Задача 1
        - [ ] Задача 2
        - [ ] Задача 3
    validations:
      required: true
  - type: textarea
    id: test-plan
    attributes:
      label: TEST PLAN (ru)
      description: Пошаговая инструкция проверки с ожидаемыми результатами
      placeholder: "1) … 2) … 3) …"
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: NOTES (ru)
      description: Ссылки, артефакты, логи (опционально)
      placeholder: "Опционально…"
    validations:
      required: false
